AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DockerImageUri:
    Type: String
    Description: URI of the Docker image to deploy
  IamRoleInstanceProfile:
    Type: String
    Description: "Specifies the Name or the Amazon Resource Name (ARN) of the instance profile associated with the IAM role for the instance"
    Default: "arn:aws:iam::581837793822:instance-profile/ecsInstanceRole"

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: AI-Dev

  ECSLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    DependsOn: ECSCluster
    Properties:
      ImageId: ami-02f21a62e8c404c55
      InstanceType: g5.xlarge
      IamInstanceProfile: !Ref IamRoleInstanceProfile
      #IamInstanceProfile: !Ref ECSTaskExecutionRole #arn:aws:iam::581837793822:role/ecsInstanceRole
      AssociatePublicIpAddress: true
      KeyName: AI-ECS-Dev
      SecurityGroups:
        - !Ref ECSServiceSecurityGroup

  ECSAutoScalingGroup:
    DependsOn: ECSLaunchConfiguration
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: 
          - subnet-00ed19bf19f9b8463 
          - subnet-001a1fa5b7ecf27be
      LaunchConfigurationName: !Ref ECSLaunchConfiguration
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      Tags:
        - Key: Name
          Value: AI-Dev
          PropagateAtLaunch: true

  Service:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerListener
    Properties:
      Cluster: AI-Dev
      TaskDefinition: !Ref TaskDefinition
      LaunchType: EC2
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      LoadBalancers:
        - ContainerName: ai-dev 
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroup

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: ai-dev
      Cpu: 256
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      Memory: 512
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ContainerDefinitions:
        - Name: ai-dev
          Image: !Ref DockerImageUri
          PortMappings:
            - ContainerPort: 3000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "ai-dev"

  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${AWS::StackName}/ai-dev"

  ECSServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-0029f60dd922eb887
      GroupDescription: Security Group for ECS Service
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-0029f60dd922eb887
      GroupDescription: Security Group for Load Balancer
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      Subnets:
        - subnet-00ed19bf19f9b8463
        - subnet-001a1fa5b7ecf27be
      SecurityGroups:
        - !Ref LBSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 3000
      Protocol: HTTP
      TargetType: instance
      VpcId: vpc-0029f60dd922eb887

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: 
      - LoadBalancer
      - TargetGroup
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  LoadBalancerSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref LBSecurityGroup
      IpProtocol: tcp
      FromPort: 3000
      ToPort: 3000
      SourceSecurityGroupId: !Ref ECSServiceSecurityGroup

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly  # Added ECR ReadOnly policy
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess  # For accessing EC2 instances