AWSTemplateFormatVersion: "2010-09-09"
Description: "The template used to create an ECS Cluster from the ECS Console."
Parameters:
  ECSClusterName:
    Type: String
    Description: "Specifies the ECS Cluster Name with which the resources would be associated"
    Default: "DevCluster"
Resources:
  ECSLaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    DependsOn: "ECSCluster"
    Properties:
      LaunchTemplateData:
        ImageId: ami-02f21a62e8c404c55
        SecurityGroupIds: 
          - sg-006d603c02d1d7e9b
        InstanceType: "g5.xlarge"
        KeyName: AI-ECS-Dev
        IamInstanceProfile:
          Arn: arn:aws:iam::581837793822:instance-profile/ecsInstanceRole
        UserData:
          Fn::Base64: |
            #!/bin/bash
            ECSClusterName="DevCluster"
            # Create directories and files for ecs configuration
            sudo mkdir -p /etc/ecs
            sudo touch /etc/ecs/ecs.config
            # Add the following lines to /etc/ecs/ecs.config
            cat <<EOT >> /etc/ecs/ecs.config
            ECS_DATADIR=/data
            ECS_ENABLE_TASK_IAM_ROLE=true
            ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
            ECS_LOGFILE=/log/ecs-agent.log
            ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]
            ECS_LOGLEVEL=info
            ECS_CLUSTER=${ECSClusterName}
            EOT
            # Pull the latest amazon-ecs-agent image
            sudo docker pull public.ecr.aws/ecs/amazon-ecs-agent:latest
            # Create directories for ecs logs and data
            sudo mkdir -p /var/log/ecs /var/lib/ecs/data
            # Run the ecs-agent container with the specified configuration
            sudo docker run --name ecs-agent \
              --detach=true \
              --restart=on-failure:10 \
              --volume=/var/run:/var/run \
              --volume=/var/log/ecs/:/log \
              --volume=/var/lib/ecs/data:/data \
              --volume=/etc/ecs:/etc/ecs \
              --volume=/etc/ecs:/etc/ecs/pki \
              --net=host \
              --env-file=/etc/ecs/ecs.config \
              amazon/amazon-ecs-agent:latest
                
  ECSAutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    DependsOn: "ECSCluster"
    Properties:
      MinSize: "1"
      MaxSize: 2
      DesiredCapacity: "1"
      LaunchTemplate:
        LaunchTemplateId: !Ref ECSLaunchTemplate
        Version: !GetAtt [ECSLaunchTemplate, LatestVersionNumber]
      VPCZoneIdentifier:
         - subnet-00ed19bf19f9b8463 
         - subnet-001a1fa5b7ecf27be
      Tags:
        - Key: "Name"
          PropagateAtLaunch: true
          Value: !Join [" - ", ["ECS Instance", !Ref ECSClusterName]]
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref ECSClusterName
      ClusterSettings:
        - Name: "containerInsights"
          Value: "disabled"
      Configuration:
        ExecuteCommandConfiguration:
          Logging: "DEFAULT"
      ServiceConnectDefaults:
        Namespace: "DevCluster"
      Tags: []
  EC2CapacityProvider:
    Type: "AWS::ECS::CapacityProvider"
    Properties:
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref ECSAutoScalingGroup
        ManagedScaling:
          Status: "ENABLED"
          TargetCapacity: 100
        ManagedTerminationProtection: "DISABLED"
  ClusterCPAssociation:
    Type: "AWS::ECS::ClusterCapacityProviderAssociations"
    DependsOn: "ECSCluster"
    Properties:
      Cluster:
        Ref: "ECSClusterName"
      CapacityProviders:
        - Ref: "EC2CapacityProvider"
      DefaultCapacityProviderStrategy:
        - Base: 0
          Weight: 1
          CapacityProvider:
            Ref: "EC2CapacityProvider"
Outputs:
  ECSCluster:
    Description: "The created cluster."
    Value:
      Ref: "ECSCluster"